/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Juliana
 */
public class WindowModificateShoppingCar extends javax.swing.JFrame {

    /**
     * Creates new form WindowModificateShoppingCar
     */
    

    
    
    
    public WindowModificateShoppingCar() {
        initComponents();
        this.setTitle("Modificate shooping car");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        refreshJlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelItemsInShoopingCar = new javax.swing.JLabel();
        buttonDeleteElementInPrePurchase = new javax.swing.JButton();
        bottonBackWindowBuyProductToWindowOption = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        squareListOfProductInPrePurchase = new javax.swing.JList();
        labelTotalAmount = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        labelIdentification = new javax.swing.JLabel();
        totalAmountSholLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelItemsInShoopingCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelItemsInShoopingCar.setForeground(new java.awt.Color(255, 255, 255));
        labelItemsInShoopingCar.setText("Items In Shooping Car");
        getContentPane().add(labelItemsInShoopingCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        buttonDeleteElementInPrePurchase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonDeleteElementInPrePurchase.setText("Delete Element");
        buttonDeleteElementInPrePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteElementInPrePurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDeleteElementInPrePurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        bottonBackWindowBuyProductToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonBackWindowBuyProductToWindowOption.setText("Back");
        bottonBackWindowBuyProductToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBackWindowBuyProductToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(bottonBackWindowBuyProductToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        squareListOfProductInPrePurchase.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(squareListOfProductInPrePurchase);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 455, 182));

        labelTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTotalAmount.setForeground(new java.awt.Color(255, 255, 255));
        labelTotalAmount.setText("TOTAL AMOUNT");
        getContentPane().add(labelTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        labelName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Name");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 62, -1, -1));

        labelPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(255, 255, 255));
        labelPrice.setText("Price");
        getContentPane().add(labelPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 62, -1, -1));

        labelQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantity.setText("Quantity");
        getContentPane().add(labelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 62, -1, -1));

        labelIdentification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelIdentification.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentification.setText("Identification");
        getContentPane().add(labelIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 62, -1, -1));
        getContentPane().add(totalAmountSholLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 87, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteElementInPrePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteElementInPrePurchaseActionPerformed
        
        /**
        
        input: identification of the product , and quantity product that have the product required 
        output:
        restriction:
        fuction: the method realice a search in the list of detail (all the product that are in the purchase car) located
        * the product that has to be reduce (the quantity). so this method verificate if the amouny available is more than 1
        * if the existence is one, the entered object has to be removed of the list, if not the only reduced the 
        * quantity of the product with the purposes of delete a product of the list
           
         **/
        
        
          if(squareListOfProductInPrePurchase.getSelectedValue() == null){
              return;
          }     
        String elementSelected = squareListOfProductInPrePurchase.getSelectedValue().toString();
        String [] chain = elementSelected.split(":");
        int identificationOfTheProduct=  Integer.parseInt(chain[3]);
  
        
        int amountOfProductInPrepurchase = Global.getAmountOfProductsListOfPrePurchase(identificationOfTheProduct);
   
        Buyer buyer = (Buyer) Global.userList.get(Global.positionOfTheUser);
        ArrayList list = buyer.getCarOfTheUser();
        PrePurchase prePurchase = (PrePurchase) list.get(Constant.POSITION_ABSOLUTE_IN_LIST_OF_PREPURCHASE);

        
        if(amountOfProductInPrepurchase == 1){
           

           int cont=0;
           for(Detail detail : prePurchase.getListDetails()){
               if(detail.getIdProduct() == identificationOfTheProduct){
                   prePurchase.getListDetails().remove(cont);
                     break;
               }

               cont=cont+1;
           }
           printJoptionPane();
            DefaultListModel name = (DefaultListModel) squareListOfProductInPrePurchase.getModel();
           name.removeAllElements();
           refreshJlist();

           
        }
        else{
          
            for(Detail detail : prePurchase.getListDetails()){
               if(detail.getIdProduct() == identificationOfTheProduct){
                
                   double newPrice= detail.getTotalPrice() - detail.getIndividualPrice();
                   detail.setTotalPrice(newPrice);
                   
                    int temp = detail.getQuantity();
                    temp = temp - 1;
                    detail.setQuantity(temp);
                    break;
               }
           }
            
           printJoptionPane();
           DefaultListModel name = (DefaultListModel) squareListOfProductInPrePurchase.getModel();
           name.removeAllElements();
           refreshJlist();
           
        }
    }//GEN-LAST:event_buttonDeleteElementInPrePurchaseActionPerformed

    private void refreshJlist(){
        
        Buyer buyer = (Buyer) Global.userList.get(Global.positionOfTheUser);
        ArrayList list = buyer.getCarOfTheUser();                
        PrePurchase prePurchase = (PrePurchase) list.get(Constant.POSITION_ABSOLUTE_IN_LIST_OF_PREPURCHASE);
        
        DefaultListModel name = (DefaultListModel) squareListOfProductInPrePurchase.getModel();
        
       double totalAmountForPrint = Global.printInSquareListProductOfPrePurchase(name, prePurchase);
       /////////////////////////////
       
       String totalAmountForPrintvalue= String.valueOf(totalAmountForPrint);
       
        totalAmountSholLabel.setText(totalAmountForPrintvalue);
       
        
        ////////////////////////////////
    }
    private void printJoptionPane(){
        JOptionPane.showMessageDialog(this,"element successfully removed");
    }
    private void bottonBackWindowBuyProductToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBackWindowBuyProductToWindowOptionActionPerformed
        // TODO add your handling code here:

        WindowBuyProduct window = new WindowBuyProduct();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonBackWindowBuyProductToWindowOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowModificateShoppingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowModificateShoppingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowModificateShoppingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowModificateShoppingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowModificateShoppingCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonBackWindowBuyProductToWindowOption;
    private javax.swing.JButton buttonDeleteElementInPrePurchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdentification;
    private javax.swing.JLabel labelItemsInShoopingCar;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelTotalAmount;
    private javax.swing.JList squareListOfProductInPrePurchase;
    private javax.swing.JLabel totalAmountSholLabel;
    // End of variables declaration//GEN-END:variables
}
