/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowCreateProductElectrodomesticInformation extends javax.swing.JFrame {

    /**
     * Creates new form WindowCreateProductElectrodomestic
     */
    public WindowCreateProductElectrodomesticInformation() {
        initComponents();
        
       //fuction: locates the window in the enter of the screen and name the window accordin to the objective of the same        
        
        this.setTitle("Create ELectrodomestic");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaObtainNameElectrodomestic = new javax.swing.JTextField();
        textAreaStateElectrodomestic = new javax.swing.JTextField();
        textAreaIdentificationElectrodomestic = new javax.swing.JTextField();
        textAreaQuantityAvailableElectrodomestic = new javax.swing.JTextField();
        labelObtainNameElectrodomestic = new javax.swing.JLabel();
        textAreaSizeApplianceElectrodomestic = new javax.swing.JTextField();
        labelIdentificationElectrodomestic = new javax.swing.JLabel();
        bottonAcceptCreateElectrodomestic = new javax.swing.JButton();
        labelPriceElectrodomestic = new javax.swing.JLabel();
        labelStateElectrodomestic = new javax.swing.JLabel();
        labelQuantityAvailableElectrodomestic = new javax.swing.JLabel();
        labelSizeApplianceElectrodomestic = new javax.swing.JLabel();
        textAreaPriceElectrodomestic = new javax.swing.JTextField();
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(textAreaObtainNameElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 250, -1));
        getContentPane().add(textAreaStateElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, -1));
        getContentPane().add(textAreaIdentificationElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 250, -1));
        getContentPane().add(textAreaQuantityAvailableElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 250, -1));

        labelObtainNameElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelObtainNameElectrodomestic.setForeground(new java.awt.Color(255, 255, 255));
        labelObtainNameElectrodomestic.setText("Name");
        getContentPane().add(labelObtainNameElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 32, -1, -1));
        getContentPane().add(textAreaSizeApplianceElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 250, -1));

        labelIdentificationElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdentificationElectrodomestic.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentificationElectrodomestic.setText("Identification");
        getContentPane().add(labelIdentificationElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, -1, -1));

        bottonAcceptCreateElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonAcceptCreateElectrodomestic.setText("Add to the System");
        bottonAcceptCreateElectrodomestic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAcceptCreateElectrodomesticActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAcceptCreateElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        labelPriceElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPriceElectrodomestic.setForeground(new java.awt.Color(255, 255, 255));
        labelPriceElectrodomestic.setText("Price");
        getContentPane().add(labelPriceElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 108, -1, -1));

        labelStateElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelStateElectrodomestic.setForeground(new java.awt.Color(255, 255, 255));
        labelStateElectrodomestic.setText("State");
        getContentPane().add(labelStateElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 149, -1, -1));

        labelQuantityAvailableElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantityAvailableElectrodomestic.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantityAvailableElectrodomestic.setText("Quantity Available");
        getContentPane().add(labelQuantityAvailableElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 187, -1, -1));

        labelSizeApplianceElectrodomestic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelSizeApplianceElectrodomestic.setForeground(new java.awt.Color(255, 255, 255));
        labelSizeApplianceElectrodomestic.setText("Size Appliance");
        getContentPane().add(labelSizeApplianceElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 227, -1, -1));
        getContentPane().add(textAreaPriceElectrodomestic, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 250, -1));

        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.setText("Back");
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed(evt);
            }
        });
        getContentPane().add(botttonBackWindowCreateProductClothesInformationTowindowCreateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonAcceptCreateElectrodomesticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAcceptCreateElectrodomesticActionPerformed
         
        //input: information about the product
        //output:
        //restriction: the identification of the product has to be unique
        //fuction: obtain all the information about the product and save the information and variables, the method is 
        //in charge to call the fuction that varificate if the identification obtain exist in the list of product, if the
        //verification pass the restriccion its created a new space of memory according to the type of product
        
        String name = textAreaObtainNameElectrodomestic.getText();
        String state = textAreaStateElectrodomestic.getText();
        String SizeAppliance = textAreaSizeApplianceElectrodomestic.getText();
        
        
        if((name.equals("")) || (textAreaIdentificationElectrodomestic.getText().equals(""))
            || (textAreaPriceElectrodomestic.getText().equals("")) || (state.equals(""))
            || (textAreaQuantityAvailableElectrodomestic.getText().equals("")) || (SizeAppliance.equals(""))){
            
            JOptionPane.showMessageDialog(this,"You cant live black space ");
        }
        else{
            int identification = Integer.parseInt(textAreaIdentificationElectrodomestic.getText());
            double price = Double.valueOf(textAreaPriceElectrodomestic.getText());
            int quantityAvailable = Integer.parseInt(textAreaQuantityAvailableElectrodomestic.getText());
        
        
            
            boolean existInList= Global.verificateIdentificationProductExistInList(identification);
            
            if(existInList == true){
                JOptionPane.showMessageDialog(this,"The Identification Already Exist");
            }
            else{
            
                if(quantityAvailable==0){
                    JOptionPane.showMessageDialog(this,"You cant insert zero in quantity space");
                }
                else{
            

                    Electrodomestic newProductElectrodomestic = new Electrodomestic(SizeAppliance,identification,Global.userName,name,price,quantityAvailable,state,"Electrodomestic");

                    double resultTotalPrice = newProductElectrodomestic.calulatePriceOfProduct(price);
                    newProductElectrodomestic.setPrice(resultTotalPrice);

                    Global.productList.add(newProductElectrodomestic);


                    textAreaObtainNameElectrodomestic.setText("");
                    textAreaStateElectrodomestic.setText("");
                    textAreaSizeApplianceElectrodomestic.setText("");
                    textAreaIdentificationElectrodomestic.setText("");
                    textAreaPriceElectrodomestic.setText("");
                    textAreaQuantityAvailableElectrodomestic.setText("");
                    JOptionPane.showMessageDialog(this, "product created successfully");
                }
            }       
        }

    }//GEN-LAST:event_bottonAcceptCreateElectrodomesticActionPerformed

    private void botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed
        
    // functions: method that open a new window according to the desition of the user (What want to do) and 
        //close the actual window        
        
        WindowCreateProduct window = new WindowCreateProduct();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductElectrodomesticInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductElectrodomesticInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductElectrodomesticInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductElectrodomesticInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowCreateProductElectrodomesticInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonAcceptCreateElectrodomestic;
    private javax.swing.JButton botttonBackWindowCreateProductClothesInformationTowindowCreateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIdentificationElectrodomestic;
    private javax.swing.JLabel labelObtainNameElectrodomestic;
    private javax.swing.JLabel labelPriceElectrodomestic;
    private javax.swing.JLabel labelQuantityAvailableElectrodomestic;
    private javax.swing.JLabel labelSizeApplianceElectrodomestic;
    private javax.swing.JLabel labelStateElectrodomestic;
    private javax.swing.JTextField textAreaIdentificationElectrodomestic;
    private javax.swing.JTextField textAreaObtainNameElectrodomestic;
    private javax.swing.JTextField textAreaPriceElectrodomestic;
    private javax.swing.JTextField textAreaQuantityAvailableElectrodomestic;
    private javax.swing.JTextField textAreaSizeApplianceElectrodomestic;
    private javax.swing.JTextField textAreaStateElectrodomestic;
    // End of variables declaration//GEN-END:variables
}
