/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Johanna
 */
public class WindowSeller extends javax.swing.JFrame {

    /**
     * Creates new form SellerWindow
     */
    public WindowSeller() {
        initComponents();
        this.setTitle("Seller Registration");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        choise = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        companyBotton = new javax.swing.JRadioButton();
        personButton = new javax.swing.JRadioButton();
        businessName = new javax.swing.JLabel();
        commercialReasonLabel = new javax.swing.JLabel();
        registerNombreCompLabel = new javax.swing.JLabel();
        acceptBotton = new javax.swing.JButton();
        CompanyRegistrationNumberTxt = new javax.swing.JTextField();
        businessNameTxt = new javax.swing.JTextField();
        commercialReasonTxt = new javax.swing.JTextField();
        backBotton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register a seller");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 14, -1, -1));

        choise.add(companyBotton);
        companyBotton.setText("Company");
        companyBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyBottonActionPerformed(evt);
            }
        });
        getContentPane().add(companyBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 67, -1, -1));

        choise.add(personButton);
        personButton.setText("Person");
        getContentPane().add(personButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 67, -1, -1));

        businessName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        businessName.setForeground(new java.awt.Color(255, 255, 255));
        businessName.setText("Business Name");
        getContentPane().add(businessName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, -1));

        commercialReasonLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        commercialReasonLabel.setForeground(new java.awt.Color(255, 255, 255));
        commercialReasonLabel.setText("Commercial Reason");
        getContentPane().add(commercialReasonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        registerNombreCompLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerNombreCompLabel.setForeground(new java.awt.Color(255, 255, 255));
        registerNombreCompLabel.setText("Company Registration Number");
        getContentPane().add(registerNombreCompLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        acceptBotton.setText("accept");
        acceptBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBottonActionPerformed(evt);
            }
        });
        getContentPane().add(acceptBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 298, -1, -1));

        CompanyRegistrationNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyRegistrationNumberTxtActionPerformed(evt);
            }
        });
        getContentPane().add(CompanyRegistrationNumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 290, -1));

        businessNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(businessNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 290, -1));

        commercialReasonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commercialReasonTxtActionPerformed(evt);
            }
        });
        getContentPane().add(commercialReasonTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 290, -1));

        backBotton.setText("BACK");
        backBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBottonActionPerformed(evt);
            }
        });
        getContentPane().add(backBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("if you are not a company can leave the blanks as they do not take into account that information");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companyBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyBottonActionPerformed

    private void CompanyRegistrationNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyRegistrationNumberTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyRegistrationNumberTxtActionPerformed

    private void businessNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_businessNameTxtActionPerformed

    private void commercialReasonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commercialReasonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commercialReasonTxtActionPerformed

    private void acceptBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBottonActionPerformed
        // TODO add your handling code here:
        
        
        
        //input: information about a user the type establishment
        //output:
        //restriction:
        //fuction: this function verificate what can of user the person want to create. if the user select a selling person
        //the method create a new memory and create a new object. if not the methos create a establishment person using a
        //new space in memory using the information obtained.Also the method establishes the new vale of the global variables
        //corresponding a the information of the user as is the position in list (principal list)
           
                
    
            if(personButton.isSelected()){
                SellingPerson newperson= new SellingPerson(Global.idUser, Global.personName, Global.ageUser, Global.emailUser, Global.hometownUser,Global.userPassword,Global.userName,"Seller");
                Global.insertar(newperson);
                int cont1 = 0;
                for(User user : Global.userList){
                    if(user.getUserName().equals(Global.userName)){
                        break;   
                    }
                    cont1 = cont1 + 1;
                }
                Global.positionOfTheUser = cont1;
                 
                 WindowOption window = new WindowOption();
                 window.setVisible(true);
                 this.dispose();
                
            }
            else if(companyBotton.isSelected()){
               
                String bussinesName= businessNameTxt.getText();
                String comercialReason= commercialReasonTxt.getText();
                boolean msj= true; 

                
                if(commercialReasonTxt.getText().equals("") || businessNameTxt.getText().equals("") || CompanyRegistrationNumberTxt.getText().equals("")){
                    msj= false;
                    JOptionPane.showMessageDialog(this, "error can not leave empty spaces");
                }

                 
                else if(msj != false){
                    int NumberOfCompany= Integer.parseInt(CompanyRegistrationNumberTxt.getText());
                    
                    Establishment newEstablishment= new Establishment(NumberOfCompany,bussinesName, comercialReason,Global.idUser,Global.personName, Global.ageUser, Global.emailUser, Global.hometownUser,Global.userPassword,Global.userName,"Seller");
                    Global.insertar(newEstablishment);

                int cont2 = 0;
                for(User user : Global.userList){
                    if(user.getUserName().equals(Global.userName)){
                        break;   
                    }
                    cont2 = cont2 + 1;
                }
                Global.positionOfTheUser = cont2;
                
                
                
                    CompanyRegistrationNumberTxt.setText("");
                    businessNameTxt.setText("");
                    commercialReasonTxt.setText("");

                    WindowOption window = new WindowOption();
                    window.setVisible(true);
                    this.dispose();
                    
                } 
                 
            }
        
            else{
                JOptionPane.showMessageDialog(this, "You must choose a seller type");
            }
    }//GEN-LAST:event_acceptBottonActionPerformed

    private void backBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBottonActionPerformed
        // TODO add your handling code here:
        WindowRegistering register = new WindowRegistering();
        register.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_backBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CompanyRegistrationNumberTxt;
    private javax.swing.JButton acceptBotton;
    private javax.swing.JButton backBotton;
    private javax.swing.JLabel businessName;
    private javax.swing.JTextField businessNameTxt;
    private javax.swing.ButtonGroup choise;
    private javax.swing.JLabel commercialReasonLabel;
    private javax.swing.JTextField commercialReasonTxt;
    private javax.swing.JRadioButton companyBotton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JRadioButton personButton;
    private javax.swing.JLabel registerNombreCompLabel;
    // End of variables declaration//GEN-END:variables
}
