/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowOption extends javax.swing.JFrame {

    /**
     * Creates new form WindowOption
     */
    public WindowOption() {
        initComponents();
        this.setTitle("Welcome");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottonSellerWindow = new javax.swing.JButton();
        bottonBuyProducts = new javax.swing.JButton();
        bottonProducts = new javax.swing.JButton();
        bottonProfile = new javax.swing.JButton();
        buttonLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottonSellerWindow.setText("Seller Window");
        bottonSellerWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonSellerWindowActionPerformed(evt);
            }
        });
        getContentPane().add(bottonSellerWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 32, 140, -1));

        bottonBuyProducts.setText("Buy Product");
        bottonBuyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBuyProductsActionPerformed(evt);
            }
        });
        getContentPane().add(bottonBuyProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 120, -1));

        bottonProducts.setText("Product Available");
        bottonProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonProductsActionPerformed(evt);
            }
        });
        getContentPane().add(bottonProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        bottonProfile.setText("Profile");
        bottonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonProfileActionPerformed(evt);
            }
        });
        getContentPane().add(bottonProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 150, -1));

        buttonLogOut.setText("Logout");
        buttonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean userHavePermissionSeller(){
        
        boolean state=false;
        for(User user : Global.userList){
            if(Global.userName.equals(user.getUserName()) && user.getType().equals("Seller")){
                state=true;
            }
        }
        return state;  
    }
    
    private boolean userHavePermissionBuyer(){
    
        boolean state=false;
        for(User user : Global.userList){
           if(Global.userName.equals(user.getUserName()) && user.getType().equals("Buyer")){
                state = true;
            }
        }
        return state;
    }
    
    
    
    private void bottonSellerWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonSellerWindowActionPerformed
        // TODO add your handling code here:
        boolean resultPermission = userHavePermissionSeller();

        if(resultPermission== true){
            WindowDesitionOfTheSeller window = new WindowDesitionOfTheSeller();
            window.setVisible(true);
            this.dispose();
        }
        else{

            JOptionPane.showMessageDialog(this,"You dont have the permission");

        }
    }//GEN-LAST:event_bottonSellerWindowActionPerformed

    private void bottonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonProfileActionPerformed
        // TODO add your handling code here:
        
        WindowProfileOfTheUser window = new WindowProfileOfTheUser();
        window.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_bottonProfileActionPerformed

    private void bottonBuyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBuyProductsActionPerformed
        // TODO add your handling code here:
        boolean resultPremissionBuyer = userHavePermissionBuyer();
        
        if(resultPremissionBuyer==true){
            WindowBuyProduct window = new WindowBuyProduct();
            window.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this,"You dont have the permission");
        }
        
 
        
        
    }//GEN-LAST:event_bottonBuyProductsActionPerformed

    private void bottonProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonProductsActionPerformed
        // TODO add your handling code here:
        WindowAvailableProductInSystem window = new WindowAvailableProductInSystem();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonProductsActionPerformed

    private void buttonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOutActionPerformed
        // TODO add your handling code here:
        
        Global.userName= "";
        WindowInitial logUot = new WindowInitial();
        logUot.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonBuyProducts;
    private javax.swing.JButton bottonProducts;
    private javax.swing.JButton bottonProfile;
    private javax.swing.JButton bottonSellerWindow;
    private javax.swing.JButton buttonLogOut;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
