/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Project1;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Johanna
 */
public class WindowRegistering extends javax.swing.JFrame {

    /**
     * Creates new form InitialWindowWindow
     */
    public WindowRegistering() {
        initComponents();
        this.setTitle("Register");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        registrationWindowTitle = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        Idlabe = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        hometownLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        IdTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        hometownTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        userNameTxt = new javax.swing.JTextField();
        backBotton = new javax.swing.JButton();
        acceptBotton = new javax.swing.JButton();
        sellerBottonw = new javax.swing.JRadioButton();
        buyerBotton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationWindowTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        registrationWindowTitle.setForeground(new java.awt.Color(255, 255, 255));
        registrationWindowTitle.setText("Registering");
        getContentPane().add(registrationWindowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 16, -1, -1));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        Idlabe.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Idlabe.setForeground(new java.awt.Color(255, 255, 255));
        Idlabe.setText("identification");
        getContentPane().add(Idlabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        ageLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel.setText("Age");
        getContentPane().add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        hometownLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hometownLabel.setForeground(new java.awt.Color(255, 255, 255));
        hometownLabel.setText("Hometown");
        getContentPane().add(hometownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("User name");
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 210, -1));

        IdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTxtActionPerformed(evt);
            }
        });
        getContentPane().add(IdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 210, -1));

        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });
        getContentPane().add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, -1));
        getContentPane().add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, -1));
        getContentPane().add(hometownTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, -1));
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 210, -1));
        getContentPane().add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 210, -1));

        backBotton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBotton.setText("BACK");
        backBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBottonActionPerformed(evt);
            }
        });
        getContentPane().add(backBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 14, -1, -1));

        acceptBotton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acceptBotton.setText("Accept");
        acceptBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBottonActionPerformed(evt);
            }
        });
        getContentPane().add(acceptBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        buttonGroup1.add(sellerBottonw);
        sellerBottonw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sellerBottonw.setText("Seller");
        sellerBottonw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellerBottonwActionPerformed(evt);
            }
        });
        getContentPane().add(sellerBottonw, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        buttonGroup1.add(buyerBotton);
        buyerBotton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buyerBotton.setText("Buyer");
        buyerBotton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyerBottonMouseClicked(evt);
            }
        });
        buyerBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerBottonActionPerformed(evt);
            }
        });
        getContentPane().add(buyerBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void IdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTxtActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void buyerBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyerBottonActionPerformed

    private void backBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBottonActionPerformed
        // TODO add your handling code here:
        WindowInitial comeback = new WindowInitial();
        comeback.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_backBottonActionPerformed

    //User newUser= new User(idUser,userName, ageUser, emailUser, hometownUser, userPassword,Global.userName ) {};
      //          Global.userList.add(newUser);
    
    private void acceptBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBottonActionPerformed
        
               /*inputs: the data typed by the user.
        output: a message on error.
        restrictions: It can not be blank spaces and can not type in strings fingerings age or identification
        functions: various information stored in global variables. if the radio button choose is a buyer person
        create a shopping cart for the buyer and the user is add to the userList. Else if the radio button 
        choosed is a Seller the user is send to the WindowSeller.

        */ 
        
        
        Global.personName= nameTxt.getText();
        
        
        Global.emailUser= emailTxt.getText();
        Global.hometownUser= hometownTxt.getText();
        Global.userName= userNameTxt.getText();
        Global.userPassword= passwordTxt.getText();
        
                

        if (Global.personName.equals("") || Global.emailUser.equals("") || Global.hometownUser.equals("") || Global.userName.equals("")
                || Global.userPassword.equals("") || IdTxt.getText().equals("") || ageTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "error can not leave empty spaces");
        }
        
        else{
            
            Global.idUser= Integer.parseInt(IdTxt.getText());
            Global.ageUser= Integer.parseInt(ageTxt.getText());
            
            int foundUser= Global.searchUser();
            if(buyerBotton.isSelected() && foundUser != 1){
                PrePurchase newPrePurchase = new PrePurchase(Global.userName, Constant.INITIAL_AMOUNT_SHOOPING_CAR);
               
                Buyer newUser= new Buyer(Constant.INITIAL_AMOUNT_PAID_USER,Constant.INITIAL_AMOUNT_PURCHASE_USER,Global.idUser,Global.userName, Global.ageUser,Global.emailUser, Global.hometownUser, Global.userPassword,Global.userName,"Buyer" );

                newUser.insertCarInList(newPrePurchase);
                Global.insertar(newUser);
                
                nameTxt.setText("");
                IdTxt.setText("");
                ageTxt.setText("");
                emailTxt.setText("");
                hometownTxt.setText("");
                userNameTxt.setText("");
                passwordTxt.setText("");

                
                
                int cont=0;
                for(User user : Global.userList){
                        if(user.getUserName().equals(Global.userName)){
                            break;
                        }
                        cont= cont +1;
                }
                
                Global.positionOfTheUser = cont;
                    WindowOption window = new WindowOption();
                    window.setVisible(true);
                    this.dispose();
            }
            else {
                if(sellerBottonw.isSelected()&& foundUser != 1){
                    
                    WindowSeller register = new WindowSeller();
                    register.setVisible(true);
                    this.dispose();
                    return;
                }
                if(foundUser == 1){
                    JOptionPane.showMessageDialog(this, "Error .. user already in the system");
                }
                else{
                    JOptionPane.showMessageDialog(this, "You must choose a user type");
                }
            }
        }
        
        
    }//GEN-LAST:event_acceptBottonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void buyerBottonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyerBottonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buyerBottonMouseClicked

    private void sellerBottonwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellerBottonwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellerBottonwActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowRegistering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowRegistering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowRegistering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowRegistering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowRegistering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdTxt;
    private javax.swing.JLabel Idlabe;
    private javax.swing.JButton acceptBotton;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backBotton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buyerBotton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel hometownLabel;
    private javax.swing.JTextField hometownTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JLabel registrationWindowTitle;
    private javax.swing.JRadioButton sellerBottonw;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
