/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowProfileOfTheUser extends javax.swing.JFrame {

    /**
     * Creates new form WindowProfileOfTheUser
     */
    public WindowProfileOfTheUser() {
       
                /*inputs: none
        output: the user information
        restrictions: none
        functions: find the user and by an interface method by which data is sent 
        all references are added to the user the especific and general information
        
        */ 
        
        initComponents();
        this.setTitle("Profile of the user");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        for(User user : Global.userList){
            if(user.getUserName().equals(Global.userName)){
                
                
                textAreaPrintUserInformation.append(" *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *" + "\n\n");
                textAreaPrintUserInformation.append(user.printUserPersonalInformation());
              if(user.getType().equalsIgnoreCase("Seller")){
                    InterfacePrintEspecificInformation sellerInterface = (InterfacePrintEspecificInformation)user;
                    textAreaPrintUserInformation.append(sellerInterface.printEspecificInformation());
                
              }
              break;
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitleOfWindowPersonalInformation = new javax.swing.JLabel();
        bottonViewRecordOfActivityInSystem = new javax.swing.JButton();
        bottonViewNoteOfTheUser = new javax.swing.JButton();
        bottonBackWindowProfileOfTheUserToWindowOption = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPrintUserInformation = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        buttonAmountOfTransactionsMade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitleOfWindowPersonalInformation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTitleOfWindowPersonalInformation.setForeground(new java.awt.Color(255, 255, 255));
        labelTitleOfWindowPersonalInformation.setText("Personal Information");
        getContentPane().add(labelTitleOfWindowPersonalInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        bottonViewRecordOfActivityInSystem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonViewRecordOfActivityInSystem.setText("View Record of Activity");
        bottonViewRecordOfActivityInSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonViewRecordOfActivityInSystemActionPerformed(evt);
            }
        });
        getContentPane().add(bottonViewRecordOfActivityInSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        bottonViewNoteOfTheUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonViewNoteOfTheUser.setText("View Note");
        bottonViewNoteOfTheUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonViewNoteOfTheUserActionPerformed(evt);
            }
        });
        getContentPane().add(bottonViewNoteOfTheUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        bottonBackWindowProfileOfTheUserToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonBackWindowProfileOfTheUserToWindowOption.setText("Back");
        bottonBackWindowProfileOfTheUserToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(bottonBackWindowProfileOfTheUserToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        textAreaPrintUserInformation.setColumns(20);
        textAreaPrintUserInformation.setRows(5);
        jScrollPane1.setViewportView(textAreaPrintUserInformation);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 65, 324, 215));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("View Reviews");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 110, -1));

        buttonAmountOfTransactionsMade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonAmountOfTransactionsMade.setText("Amount of Transactions Made");
        buttonAmountOfTransactionsMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAmountOfTransactionsMadeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAmountOfTransactionsMade, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed
        // TODO add your handling code here:
        WindowOption window = new WindowOption();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed

   
    
    private void bottonViewNoteOfTheUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonViewNoteOfTheUserActionPerformed
        
               /*inputs: none
        output: the user note
        restrictions: none
        functions: the user is find and depend of the type the note is calculated 
        (the note take the value of the diferent funtion depending of the type of user)
        finaly the value obtained is printed in the window.
        */ 
        
        double note = 0;
        for(User user : Global.userList){
            if(user.getUserName().equals(Global.userName)){
                if(user.getType().equalsIgnoreCase("Seller")){
                  note = user.calculateNote();
                }
                else{
                    note = user.calculateNote();

                }
            }
        }
        JOptionPane.showMessageDialog(this,"Note: "+ note);
        
        
        
    }//GEN-LAST:event_bottonViewNoteOfTheUserActionPerformed

    private void bottonViewRecordOfActivityInSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonViewRecordOfActivityInSystemActionPerformed
        // TODO add your handling code here:
        WindowShowActivityOfTheUser window = new WindowShowActivityOfTheUser();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonViewRecordOfActivityInSystemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        WindowShowReviewOfTheUser window = new WindowShowReviewOfTheUser();
        window.setVisible(true);
        this.dispose();
                
    }//GEN-LAST:event_jButton1ActionPerformed

    public void printAmountOfPurchases(){
        double totalAmountOfPurchases = 0;
        
        if(Global.purchaseList.isEmpty()){
            JOptionPane.showMessageDialog(this,"Purchases: "+ totalAmountOfPurchases);
        }
        else{
            for(Purchase purchase : Global.purchaseList){
                if(purchase.getUserName().equals(Global.userName)){
                    
                    for(PurchaseDetail purchaseDetail : purchase.getListOfPurchaseDetails()){
                      
                  
                     totalAmountOfPurchases = totalAmountOfPurchases + purchaseDetail.getTotalPrice();
                
                    }

                }
            }
         
            JOptionPane.showMessageDialog(this,"Purchases: "+ totalAmountOfPurchases);
        }
        
    }
    
    public void printAmountOfSales(){
        
        double totalAmountOfSales = 0;
        
        if(Global.purchaseList.isEmpty()){
            JOptionPane.showMessageDialog(this,"Sales: "+ totalAmountOfSales);
        }
        else{
            
            for(Purchase purchase : Global.purchaseList){
               for(PurchaseDetail purchaseDetail : purchase.getListOfPurchaseDetails()){
                   if(purchaseDetail.getSellerUserName().equals(Global.userName)){
                       totalAmountOfSales= totalAmountOfSales + purchaseDetail.getTotalPrice();
                   }
               }
            }
            
            JOptionPane.showMessageDialog(this,"Sales: "+ totalAmountOfSales);
        }        
    }
    
    private void buttonAmountOfTransactionsMadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAmountOfTransactionsMadeActionPerformed
        // TODO add your handling code here:
        
        String typeOfUser = "";
        for(User user : Global.userList){
            if(user.getUserName().equals(Global.userName)){
                typeOfUser = user.getType();
                break;
            }
        }
        if(typeOfUser.equals("Buyer")){
            printAmountOfPurchases();
        }
        else{
            printAmountOfSales();
        }
        
             
    }//GEN-LAST:event_buttonAmountOfTransactionsMadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowProfileOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowProfileOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowProfileOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowProfileOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowProfileOfTheUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonBackWindowProfileOfTheUserToWindowOption;
    private javax.swing.JButton bottonViewNoteOfTheUser;
    private javax.swing.JButton bottonViewRecordOfActivityInSystem;
    private javax.swing.JButton buttonAmountOfTransactionsMade;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitleOfWindowPersonalInformation;
    private javax.swing.JTextArea textAreaPrintUserInformation;
    // End of variables declaration//GEN-END:variables
}
