/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

/**
 *
 * @author Juliana
 */
public class WindowDesitionOfTheSeller extends javax.swing.JFrame {

    /**
     * Creates new form WindowDesitionOfTheSeller
     */
    public WindowDesitionOfTheSeller() {
        initComponents();
        this.setTitle("Desition of the seller");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSellProduct = new javax.swing.JButton();
        buttonConsultSalesData = new javax.swing.JButton();
        buttonBackWindowDesitionOfTheSellerToWindowOption = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSellProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonSellProduct.setText("Sell Product");
        buttonSellProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSellProductActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSellProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        buttonConsultSalesData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonConsultSalesData.setText("Consult Sales Data");
        buttonConsultSalesData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultSalesDataActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConsultSalesData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        buttonBackWindowDesitionOfTheSellerToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonBackWindowDesitionOfTheSellerToWindowOption.setText("Back");
        buttonBackWindowDesitionOfTheSellerToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackWindowDesitionOfTheSellerToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBackWindowDesitionOfTheSellerToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Qualifying buyers of its products");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSellProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSellProductActionPerformed
        // TODO add your handling code here:
        
        WindowCreateProduct window = new WindowCreateProduct();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonSellProductActionPerformed

    private void buttonConsultSalesDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultSalesDataActionPerformed
        // TODO add your handling code here:
        WindowConsultOfTheSales window = new WindowConsultOfTheSales();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonConsultSalesDataActionPerformed

    private void buttonBackWindowDesitionOfTheSellerToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackWindowDesitionOfTheSellerToWindowOptionActionPerformed
        // TODO add your handling code here:
        WindowOption window = new WindowOption();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackWindowDesitionOfTheSellerToWindowOptionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        WindowCreateReviewSeller window = new WindowCreateReviewSeller();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowDesitionOfTheSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowDesitionOfTheSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowDesitionOfTheSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowDesitionOfTheSeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowDesitionOfTheSeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackWindowDesitionOfTheSellerToWindowOption;
    private javax.swing.JButton buttonConsultSalesData;
    private javax.swing.JButton buttonSellProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
