/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowCreateProductClothesInformation extends javax.swing.JFrame {

    /**
     * Creates new form WindowCreateProductGroceriesInformation
     */
    public WindowCreateProductClothesInformation() {
        initComponents();
        
        //fuction: locates the window in the enter of the screen and name the window accordin to the objective of the same
        
          
        this.setTitle("Create clothe");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelObtainNameClothes = new javax.swing.JLabel();
        labelIdentificationClothes = new javax.swing.JLabel();
        labelPriceClothes = new javax.swing.JLabel();
        labelStateClothes = new javax.swing.JLabel();
        labelQuantityAvailableClothes = new javax.swing.JLabel();
        labelObjectivePublicClothes = new javax.swing.JLabel();
        textAreaObtainNameClothes = new javax.swing.JTextField();
        textAreaIdentificationClothes = new javax.swing.JTextField();
        textAreaPriceClothes = new javax.swing.JTextField();
        textAreaStateClothes = new javax.swing.JTextField();
        textAreaQuantityAvailableClothes = new javax.swing.JTextField();
        textAreaObjectivePublicClothes = new javax.swing.JTextField();
        bottonAcceptCreateClothes = new javax.swing.JButton();
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelObtainNameClothes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelObtainNameClothes.setForeground(new java.awt.Color(255, 255, 255));
        labelObtainNameClothes.setText("Name");
        getContentPane().add(labelObtainNameClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 35, -1, -1));

        labelIdentificationClothes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdentificationClothes.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentificationClothes.setText("Identification");
        getContentPane().add(labelIdentificationClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 73, -1, -1));

        labelPriceClothes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPriceClothes.setForeground(new java.awt.Color(255, 255, 255));
        labelPriceClothes.setText("Price");
        getContentPane().add(labelPriceClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 111, -1, -1));

        labelStateClothes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelStateClothes.setForeground(new java.awt.Color(255, 255, 255));
        labelStateClothes.setText("State");
        getContentPane().add(labelStateClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 152, -1, -1));

        labelQuantityAvailableClothes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantityAvailableClothes.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantityAvailableClothes.setText("Quantity Available");
        getContentPane().add(labelQuantityAvailableClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 190, -1, -1));

        labelObjectivePublicClothes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelObjectivePublicClothes.setForeground(new java.awt.Color(255, 255, 255));
        labelObjectivePublicClothes.setText("Objective Public");
        getContentPane().add(labelObjectivePublicClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 230, -1, -1));
        getContentPane().add(textAreaObtainNameClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, -1));
        getContentPane().add(textAreaIdentificationClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 237, -1));
        getContentPane().add(textAreaPriceClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 240, -1));
        getContentPane().add(textAreaStateClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 240, -1));
        getContentPane().add(textAreaQuantityAvailableClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 240, -1));
        getContentPane().add(textAreaObjectivePublicClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 240, -1));

        bottonAcceptCreateClothes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonAcceptCreateClothes.setText("Add to the System");
        bottonAcceptCreateClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAcceptCreateClothesActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAcceptCreateClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.setText("Back");
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed(evt);
            }
        });
        getContentPane().add(botttonBackWindowCreateProductClothesInformationTowindowCreateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonAcceptCreateClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAcceptCreateClothesActionPerformed
        // TODO add your handling code here:
      
        //input: information about the product
        //output:
        //restriction: the identification of the product has to be unique
        //fuction: obtain all the information about the product and save the information and variables, the method is 
        //in charge to call the fuction that varificate if the identification obtain exist in the list of product, if the
        //verification pass the restriccion its created a new space of memory according to the type of product
        
        String name = textAreaObtainNameClothes.getText();
        String state = textAreaStateClothes.getText();
        String objectivePublic = textAreaObjectivePublicClothes.getText();
        
        
        if((name.equals("")) || (textAreaIdentificationClothes.getText().equals(""))
            || (textAreaPriceClothes.getText().equals("")) || (state.equals(""))
            || (textAreaQuantityAvailableClothes.getText().equals("")) || (objectivePublic.equals(""))){
            
            JOptionPane.showMessageDialog(this,"You cant live black space ");
        }
        else{
            int identification = Integer.parseInt(textAreaIdentificationClothes.getText());
            double price = Double.valueOf(textAreaPriceClothes.getText());
            int quantityAvailable = Integer.parseInt(textAreaQuantityAvailableClothes.getText());
            
            
            boolean existInList= Global.verificateIdentificationProductExistInList(identification);
            
            if(existInList == true){
                JOptionPane.showMessageDialog(this,"The Identification Already Exist");
            }
            else{
            
                if(quantityAvailable==0){
                    JOptionPane.showMessageDialog(this,"You cant insert zero in quantity space");
                }
                else{

                    Clothe newProductClothes = new Clothe(objectivePublic,identification,Global.userName,name,price,quantityAvailable,state,"Clothe");

                    double resultTotalPrice = newProductClothes.calulatePriceOfProduct(price);
                    newProductClothes.setPrice(resultTotalPrice);

                    Global.productList.add(newProductClothes);

                    textAreaObtainNameClothes.setText("");
                    textAreaStateClothes.setText("");
                    textAreaObjectivePublicClothes.setText("");
                    textAreaIdentificationClothes.setText("");
                    textAreaPriceClothes.setText("");
                    textAreaQuantityAvailableClothes.setText("");
                    
                    JOptionPane.showMessageDialog(this, "product created successfully");

                }
            }
        }     
        
    }//GEN-LAST:event_bottonAcceptCreateClothesActionPerformed

    private void botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed
        // TODO add your handling code here:

        
     // functions: method that open a new window according to the desition of the user (What want to do) and 
        //close the actual window
        
        WindowCreateProduct window = new WindowCreateProduct();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductClothesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductClothesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductClothesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductClothesInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowCreateProductClothesInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonAcceptCreateClothes;
    private javax.swing.JButton botttonBackWindowCreateProductClothesInformationTowindowCreateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIdentificationClothes;
    private javax.swing.JLabel labelObjectivePublicClothes;
    private javax.swing.JLabel labelObtainNameClothes;
    private javax.swing.JLabel labelPriceClothes;
    private javax.swing.JLabel labelQuantityAvailableClothes;
    private javax.swing.JLabel labelStateClothes;
    private javax.swing.JTextField textAreaIdentificationClothes;
    private javax.swing.JTextField textAreaObjectivePublicClothes;
    private javax.swing.JTextField textAreaObtainNameClothes;
    private javax.swing.JTextField textAreaPriceClothes;
    private javax.swing.JTextField textAreaQuantityAvailableClothes;
    private javax.swing.JTextField textAreaStateClothes;
    // End of variables declaration//GEN-END:variables
}
