/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

/**
 *
 * @author Juliana
 */
public class WindowShowActivityOfTheUser extends javax.swing.JFrame {

    /**
     * Creates new form WindowShowActivityOfTheUser
     */
    


    
    public WindowShowActivityOfTheUser() {
        initComponents();
        
        //fuction: the method call a diferent function to print the information
        this.setTitle("Activity Of The User");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
     
        String type;
        for(User user : Global.userList){
            if(user.getUserName().equals(Global.userName)){
                type = user.getType();
                InterfacePrintActivityOfTheUser inter = (InterfacePrintActivityOfTheUser) user;
                if(type.equalsIgnoreCase("Seller")){
                        inter.printActivityOfTheUser();
                        break;
                }
                else{

                    inter.printActivityOfTheUser();
                    break;

                }               
            }
        }
        for(String string : Global.tempArrayToPrintActivityUser){
            textAreaPrintUserInformation.append(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelActivityOfTheUser = new javax.swing.JLabel();
        bottonBackWindowProfileOfTheUserToWindowOption = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaPrintUserInformation = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelActivityOfTheUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelActivityOfTheUser.setForeground(new java.awt.Color(255, 255, 255));
        labelActivityOfTheUser.setText("Activity Of The User");
        getContentPane().add(labelActivityOfTheUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 28, -1, -1));

        bottonBackWindowProfileOfTheUserToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonBackWindowProfileOfTheUserToWindowOption.setText("Back");
        bottonBackWindowProfileOfTheUserToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(bottonBackWindowProfileOfTheUserToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        textAreaPrintUserInformation.setColumns(20);
        textAreaPrintUserInformation.setRows(5);
        jScrollPane1.setViewportView(textAreaPrintUserInformation);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 430, 180));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed
        // TODO add your handling code here:
        
        
   
        
        WindowProfileOfTheUser window = new WindowProfileOfTheUser();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonBackWindowProfileOfTheUserToWindowOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowShowActivityOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowShowActivityOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowShowActivityOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowShowActivityOfTheUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowShowActivityOfTheUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonBackWindowProfileOfTheUserToWindowOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelActivityOfTheUser;
    private javax.swing.JTextArea textAreaPrintUserInformation;
    // End of variables declaration//GEN-END:variables
}
