/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowCreateProductFurnitureInformation extends javax.swing.JFrame {

    /**
     * Creates new form WindowCreateProductClothesInformation
     */
    public WindowCreateProductFurnitureInformation() {
        initComponents();
        
        //fuction: locates the window in the enter of the screen and name the window accordin to the objective of the same
       
        
        this.setTitle("Create Furniture");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAreaPriceFurniture = new javax.swing.JTextField();
        textAreaStateFurniture = new javax.swing.JTextField();
        textAreaQuantityAvailableFurniture = new javax.swing.JTextField();
        labelObtainNameFurniture = new javax.swing.JLabel();
        textAreaTypeOfMaterialFurniture = new javax.swing.JTextField();
        labelIdentificationFurniture = new javax.swing.JLabel();
        bottonAcceptCreateFurniture = new javax.swing.JButton();
        labelPriceFurniture = new javax.swing.JLabel();
        labelStateFurniture = new javax.swing.JLabel();
        labelQuantityAvailableFurniture = new javax.swing.JLabel();
        labelTypeOfMaterialFurniture = new javax.swing.JLabel();
        textAreaObtainNameFurniture = new javax.swing.JTextField();
        textAreaIdentificationFurniture = new javax.swing.JTextField();
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(textAreaPriceFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 250, -1));
        getContentPane().add(textAreaStateFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 250, -1));
        getContentPane().add(textAreaQuantityAvailableFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 250, -1));

        labelObtainNameFurniture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelObtainNameFurniture.setForeground(new java.awt.Color(255, 255, 255));
        labelObtainNameFurniture.setText("Name");
        getContentPane().add(labelObtainNameFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 32, -1, -1));
        getContentPane().add(textAreaTypeOfMaterialFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 250, -1));

        labelIdentificationFurniture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdentificationFurniture.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentificationFurniture.setText("Identification");
        getContentPane().add(labelIdentificationFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 70, -1, -1));

        bottonAcceptCreateFurniture.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonAcceptCreateFurniture.setText("Add to the System");
        bottonAcceptCreateFurniture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAcceptCreateFurnitureActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAcceptCreateFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        labelPriceFurniture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelPriceFurniture.setForeground(new java.awt.Color(255, 255, 255));
        labelPriceFurniture.setText("Price");
        getContentPane().add(labelPriceFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 118, -1, -1));

        labelStateFurniture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelStateFurniture.setForeground(new java.awt.Color(255, 255, 255));
        labelStateFurniture.setText("State");
        getContentPane().add(labelStateFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 159, -1, -1));

        labelQuantityAvailableFurniture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantityAvailableFurniture.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantityAvailableFurniture.setText("Quantity Available");
        getContentPane().add(labelQuantityAvailableFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 197, -1, -1));

        labelTypeOfMaterialFurniture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTypeOfMaterialFurniture.setForeground(new java.awt.Color(255, 255, 255));
        labelTypeOfMaterialFurniture.setText("Type Of Material");
        getContentPane().add(labelTypeOfMaterialFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 237, -1, -1));
        getContentPane().add(textAreaObtainNameFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 250, -1));
        getContentPane().add(textAreaIdentificationFurniture, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 250, -1));

        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.setText("Back");
        botttonBackWindowCreateProductClothesInformationTowindowCreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed(evt);
            }
        });
        getContentPane().add(botttonBackWindowCreateProductClothesInformationTowindowCreateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    
    private void bottonAcceptCreateFurnitureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAcceptCreateFurnitureActionPerformed
  
        //input: information about the product
        //output:
        //restriction: the identification of the product has to be unique
        //fuction: obtain all the information about the product and save the information and variables, the method is 
        //in charge to call the fuction that varificate if the identification obtain exist in the list of product, if the
        //verification pass the restriccion its created a new space of memory according to the type of product
         
        
        String name = textAreaObtainNameFurniture.getText();
        String state = textAreaStateFurniture.getText();
        String typeOfMaterial = textAreaTypeOfMaterialFurniture.getText();
        
        
        if((name.equals("")) || (textAreaIdentificationFurniture.getText().equals(""))
            || (textAreaPriceFurniture.getText().equals("")) || (state.equals(""))
            || (textAreaQuantityAvailableFurniture.getText().equals("")) || (typeOfMaterial.equals(""))){
            
            JOptionPane.showMessageDialog(this,"You cant live black space ");
        }
        else{
            
            int identification = Integer.parseInt(textAreaIdentificationFurniture.getText());
            double price = Double.valueOf(textAreaPriceFurniture.getText());
            int quantityAvailable = Integer.parseInt(textAreaQuantityAvailableFurniture.getText());
        
            
            
            boolean existInList= Global.verificateIdentificationProductExistInList(identification);
            
            if(existInList == true){
                JOptionPane.showMessageDialog(this,"The Identification Already Exist");
            }
            else{
            

                if(quantityAvailable==0){
                    JOptionPane.showMessageDialog(this,"You cant insert zero in quantity space");
                }
                else{
                    Furniture newProductFurniture = new Furniture(typeOfMaterial,identification,Global.userName,name,price,quantityAvailable,state,"Furniture");

                    double resultTotalPrice = newProductFurniture.calulatePriceOfProduct(price);
                    newProductFurniture.setPrice(resultTotalPrice);

                    Global.productList.add(newProductFurniture);


                    textAreaObtainNameFurniture.setText("");
                    textAreaStateFurniture.setText("");
                    textAreaTypeOfMaterialFurniture.setText("");
                    textAreaIdentificationFurniture.setText("");
                    textAreaPriceFurniture.setText("");
                    textAreaQuantityAvailableFurniture.setText("");
                    
                    JOptionPane.showMessageDialog(this, "product created successfully");
                }
            }
        
        }

    }//GEN-LAST:event_bottonAcceptCreateFurnitureActionPerformed

    private void botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed
        
    // functions: method that open a new window according to the desition of the user (What is want to do) and 
        //close the actual window
        
        WindowCreateProduct window = new WindowCreateProduct();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botttonBackWindowCreateProductClothesInformationTowindowCreateProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductFurnitureInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductFurnitureInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductFurnitureInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProductFurnitureInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowCreateProductFurnitureInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonAcceptCreateFurniture;
    private javax.swing.JButton botttonBackWindowCreateProductClothesInformationTowindowCreateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIdentificationFurniture;
    private javax.swing.JLabel labelObtainNameFurniture;
    private javax.swing.JLabel labelPriceFurniture;
    private javax.swing.JLabel labelQuantityAvailableFurniture;
    private javax.swing.JLabel labelStateFurniture;
    private javax.swing.JLabel labelTypeOfMaterialFurniture;
    private javax.swing.JTextField textAreaIdentificationFurniture;
    private javax.swing.JTextField textAreaObtainNameFurniture;
    private javax.swing.JTextField textAreaPriceFurniture;
    private javax.swing.JTextField textAreaQuantityAvailableFurniture;
    private javax.swing.JTextField textAreaStateFurniture;
    private javax.swing.JTextField textAreaTypeOfMaterialFurniture;
    // End of variables declaration//GEN-END:variables
}
