/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Johanna
 */
public class WindowLogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public WindowLogIn() {
        initComponents();
        this.setTitle("Log in");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logIn = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        acceptBotton = new javax.swing.JButton();
        userNameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        backBotton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logIn.setForeground(new java.awt.Color(255, 255, 255));
        logIn.setText("Log in");
        getContentPane().add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("User name");
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        acceptBotton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acceptBotton.setText("Accept");
        acceptBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBottonActionPerformed(evt);
            }
        });
        getContentPane().add(acceptBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 223, -1));

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 223, -1));

        backBotton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backBotton.setText("BACK");
        backBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBottonActionPerformed(evt);
            }
        });
        getContentPane().add(backBotton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void acceptBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBottonActionPerformed
        
         /**
         input: information about the user obtain using graphic interface
        output:
        restriction: the username and the password must to be the same that one of the informacition located in the list
        users
        fuction: obtain the informatio about the user and search in the principal window that the information obtained
        is the same as any datal located in the principal list. if the information is the same the method allow entry
        of the user in the program. if not will impede the entry
           
         **/
        
        
        Global.userName= userNameTxt.getText();
        String password= passwordTxt.getText();
        boolean msj= false;
        if(Global.userName.isEmpty()){
            msj= true;
            JOptionPane.showMessageDialog(this, "error can not leave empty spaces");
        }
        
        else if(Global.userList != null){
            int position=0;
            for(User user : Global.userList){
                if(user.getUserName().equals(Global.userName) && user.getPassword().equals(password)){
                    Global.positionOfTheUser = position;
                    msj= true;
                    WindowOption window = new WindowOption();
                    window.setVisible(true);
                    this.dispose();
                }
                position = position + 1;
             }
        }
        if(msj != true){
            JOptionPane.showMessageDialog(this, "Error the user not exist.."); 
        }
       
    }//GEN-LAST:event_acceptBottonActionPerformed

    private void backBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBottonActionPerformed
        // TODO add your handling code here:
        WindowInitial comeback = new WindowInitial();
        comeback.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBotton;
    private javax.swing.JButton backBotton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logIn;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
