/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowCreateProduct extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public WindowCreateProduct() {
        initComponents();
       
                /*inputs: none
        output: Kind of Product will become visible above the screen
        restrictions: none
        functions:none
        */   
        
        this.setTitle("Kind of Product");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupChoseTypeProduct = new javax.swing.ButtonGroup();
        bottonAcceptVarificateAreaOfProduct = new javax.swing.JButton();
        buttonBackWindowCreateProductToWindowOption = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioButtonFurniture = new javax.swing.JRadioButton();
        radioButtonElectrodomestics = new javax.swing.JRadioButton();
        radioButtonClothes = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottonAcceptVarificateAreaOfProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonAcceptVarificateAreaOfProduct.setText("Accept");
        bottonAcceptVarificateAreaOfProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAcceptVarificateAreaOfProductActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAcceptVarificateAreaOfProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 232, -1, -1));

        buttonBackWindowCreateProductToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonBackWindowCreateProductToWindowOption.setText("Back");
        buttonBackWindowCreateProductToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackWindowCreateProductToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBackWindowCreateProductToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select the kind of product that you want to sell ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 21, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Types", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        buttonGroupChoseTypeProduct.add(radioButtonFurniture);
        radioButtonFurniture.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonFurniture.setText("Furniture");

        buttonGroupChoseTypeProduct.add(radioButtonElectrodomestics);
        radioButtonElectrodomestics.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonElectrodomestics.setText("Electrodomestics");

        buttonGroupChoseTypeProduct.add(radioButtonClothes);
        radioButtonClothes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioButtonClothes.setText("Clothes");
        radioButtonClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonClothesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(radioButtonFurniture)
                .addGap(18, 18, 18)
                .addComponent(radioButtonElectrodomestics)
                .addGap(18, 18, 18)
                .addComponent(radioButtonClothes)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonFurniture)
                    .addComponent(radioButtonElectrodomestics)
                    .addComponent(radioButtonClothes))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackWindowCreateProductToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackWindowCreateProductToWindowOptionActionPerformed

                /*
        functions: the current screen is closed after sending the user to the screen WindowBuyProduct
        */

        WindowDesitionOfTheSeller window = new WindowDesitionOfTheSeller();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackWindowCreateProductToWindowOptionActionPerformed

    private void radioButtonClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonClothesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonClothesActionPerformed

    private void bottonAcceptVarificateAreaOfProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAcceptVarificateAreaOfProductActionPerformed
        

                /*inputs: the user selected radio button
        output: send the user to some window (depends in how option the user choose)
        or send an advice to the user.
        restrictions: the user can´t live empty spaces
        functions: the option choose for the user by the radio button send 
        to the user to the difetents windows for create some type of product (Electrodomestic
        Furniture or Clothes)
        */  
        
        if( ! radioButtonClothes.isSelected() && ! radioButtonElectrodomestics.isSelected() && ! radioButtonFurniture.isSelected() ){
            return;
        }
        
        
        if(radioButtonFurniture.isSelected()){
            WindowCreateProductFurnitureInformation window = new WindowCreateProductFurnitureInformation();
            window.setVisible(true);
            this.dispose();
            
        }
        else if(radioButtonElectrodomestics.isSelected()){
            WindowCreateProductElectrodomesticInformation window = new WindowCreateProductElectrodomesticInformation();
            window.setVisible(true);
            this.dispose();
        }
        else if(radioButtonClothes.isSelected()){
            WindowCreateProductClothesInformation window = new WindowCreateProductClothesInformation();
            window.setVisible(true);
            this.dispose();
            
        }
        else{
            JOptionPane.showMessageDialog(this,"You cant live black space ");
        }
           
    }//GEN-LAST:event_bottonAcceptVarificateAreaOfProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCreateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowCreateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonAcceptVarificateAreaOfProduct;
    private javax.swing.JButton buttonBackWindowCreateProductToWindowOption;
    private javax.swing.ButtonGroup buttonGroupChoseTypeProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioButtonClothes;
    private javax.swing.JRadioButton radioButtonElectrodomestics;
    private javax.swing.JRadioButton radioButtonFurniture;
    // End of variables declaration//GEN-END:variables
}
