/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Juliana
 */
public class WindowBuyProductElectrodomestics extends javax.swing.JFrame {

    /**
     * Creates new form WindowBuyProductElectrodomestics
     */
    public WindowBuyProductElectrodomestics() {
              
        //input:
        //output:
        //restriction:
        //fuction: locates the window in the enter of the screen and name the window accordin to the objective of the same
        // also call the methos that is in charge tha print all the information about prduct that are available to
        //buy
        
        initComponents();
         this.setTitle("Items for sale");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        
        
        DefaultListModel name = (DefaultListModel) squareListOfProduct.getModel();
        Global.printInSquareListAvailableProduct(name,"Electrodomestic");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bottonAddProductToCar = new javax.swing.JButton();
        bottonBackWindowBuyProductToWindowOption = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        squareListOfProduct = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Items For Sale");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        bottonAddProductToCar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonAddProductToCar.setText("Add To Car");
        bottonAddProductToCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonAddProductToCarActionPerformed(evt);
            }
        });
        getContentPane().add(bottonAddProductToCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        bottonBackWindowBuyProductToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonBackWindowBuyProductToWindowOption.setText("Back");
        bottonBackWindowBuyProductToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBackWindowBuyProductToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(bottonBackWindowBuyProductToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        squareListOfProduct.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(squareListOfProduct);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 54, 227, 182));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 256, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonAddProductToCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonAddProductToCarActionPerformed
        

        //input:
        //output:
        //restriction: the person must select the product that want buy
        //fuction: function in charge to call some methos that are necesary to add a product to the shooping car
        // first the method hae to check that the quantity obtain un the list of product is greater that the quantity
        //obtain in the list of prepurchase. after that the method call the function in charge to add a product in the 
        //purchase car
        
        if(squareListOfProduct.getSelectedValue() == null){
              return;
          }  
       
        String elementSelected = squareListOfProduct.getSelectedValue().toString();
        
        String [] chain = elementSelected.split(":");
        int identificationOfTheProduct=  Integer.parseInt(chain[5]);
        
        
        int amountProductAvailableInListOfPrePurchase = Global.getAmountOfProductsListOfPrePurchase(identificationOfTheProduct);
        
       int amountProductAvailableInListOfProduct = Global.getAmountOfProductsListOfProduct(identificationOfTheProduct);
        
        
     
        if(amountProductAvailableInListOfPrePurchase >= amountProductAvailableInListOfProduct){
            JOptionPane.showMessageDialog(this,"There is not enough inventory for the purchase");
        }
        else{
            Global.insertProductsInShoopingCar(amountProductAvailableInListOfPrePurchase, identificationOfTheProduct);
            JOptionPane.showMessageDialog(this,"It has been added to the product correctly");
         
        
        }
        
    }//GEN-LAST:event_bottonAddProductToCarActionPerformed

    private void bottonBackWindowBuyProductToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBackWindowBuyProductToWindowOptionActionPerformed
        
        // functions: method that open a new window accordin to the desition of the user (What want to do) and 
        //close the actual window

        WindowBuyProduct window = new WindowBuyProduct();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonBackWindowBuyProductToWindowOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowBuyProductElectrodomestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowBuyProductElectrodomestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowBuyProductElectrodomestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowBuyProductElectrodomestics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowBuyProductElectrodomestics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonAddProductToCar;
    private javax.swing.JButton bottonBackWindowBuyProductToWindowOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList squareListOfProduct;
    // End of variables declaration//GEN-END:variables
}
