/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.DefaultListModel;

/**
 *
 * @author Juliana
 */
public class WindowConsultOfTheSales extends javax.swing.JFrame {

    /**
     * Creates new form WindowConsultOfTheSales
     */
    
    public void printItemsSoldInTheSquare(){

        //input:
        //output:
        //restriction:
        //fuction: search in the list of purchase and for each purchase search in the list of detail (product that have) searching
        //the name of ther user that is actually login. if the name is the same the method add the information about the
        //purchase, if not the method informs the user that not have product sold
        
        boolean havePurchaseDetails = false;
        DefaultListModel name = (DefaultListModel) squareListOfProductSold.getModel();
        
        for(Purchase purchase : Global.purchaseList){
            for(PurchaseDetail purchaseDetails : purchase.getListOfPurchaseDetails()){
                if(purchaseDetails.getSellerUserName().equals(Global.userName)){
                    if(havePurchaseDetails == false){
                        havePurchaseDetails = true;
                    }
                    name.addElement(purchaseDetails.getNameProduct() + "                            " + purchaseDetails.getQuantity() + "                           " + purchase.getUserName());
                }
            }
        }
        if(havePurchaseDetails == false){
            name.addElement("you have not sold any product");

        }
    }
    
    public void printItemsUnSoldInTheSquare(){

        //input:
        //output:
        //restriction:
        //fuction: search in the list of product searching the name of ther user that is actually login. 
        //if the name is the same the method add the information about the product, if not the method informs 
        //the user that not have any product created in the systems with his name (not have unsold product)      
        
        boolean haveProductInSystem = false;
        
        DefaultListModel name = (DefaultListModel) squareListOfProductUnsold.getModel();
        
        for(Product product : Global.productList){
            if(product.getUserName().equals(Global.userName)){
                if(haveProductInSystem == false){
                    haveProductInSystem = true;
                }
                name.addElement(product.getName() + "                        " + product.getQuantityAvailable()+"                          " + product.getIdProduct() );
 
            }
        }
        if(haveProductInSystem == false){
             name.addElement("You have not added any products to the system");
 
        }
    }
    
    public WindowConsultOfTheSales(){
        initComponents();
        
        //input:
        //output:
        //restriction:
        //fuction: locates the window in the enter of the screen and name the window according to the objective of the same
        // also call the method that is in charge that print all the information about the seller, as the information about
        //the sold product or the unsold product
       
        
        this.setTitle("Items in the System");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
       
        
        printItemsSoldInTheSquare();
        printItemsUnSoldInTheSquare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        labelItemsSold = new javax.swing.JLabel();
        labelIdentification = new javax.swing.JLabel();
        buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSeller = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        squareListOfProductUnsold = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        squareListOfProductSold = new javax.swing.JList();
        labelName1 = new javax.swing.JLabel();
        labelQuantity1 = new javax.swing.JLabel();
        labelIdentification1 = new javax.swing.JLabel();
        labelItemsUnsold = new javax.swing.JLabel();
        labelItemsInTheSystem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Name");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        labelQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantity.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantity.setText("Quantity");
        getContentPane().add(labelQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        labelItemsSold.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelItemsSold.setForeground(new java.awt.Color(255, 255, 255));
        labelItemsSold.setText("Items Sold");
        getContentPane().add(labelItemsSold, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        labelIdentification.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdentification.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentification.setText("Identification");
        getContentPane().add(labelIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSeller.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSeller.setText("Back");
        buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSellerActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        squareListOfProductUnsold.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(squareListOfProductUnsold);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 300, 182));

        squareListOfProductSold.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(squareListOfProductSold);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 290, 182));

        labelName1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName1.setForeground(new java.awt.Color(255, 255, 255));
        labelName1.setText("Name");
        getContentPane().add(labelName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        labelQuantity1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantity1.setForeground(new java.awt.Color(255, 255, 255));
        labelQuantity1.setText("Quantity");
        getContentPane().add(labelQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        labelIdentification1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdentification1.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentification1.setText("Buyer");
        getContentPane().add(labelIdentification1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, -1));

        labelItemsUnsold.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelItemsUnsold.setForeground(new java.awt.Color(255, 255, 255));
        labelItemsUnsold.setText("Items Unsold");
        getContentPane().add(labelItemsUnsold, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        labelItemsInTheSystem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelItemsInTheSystem.setForeground(new java.awt.Color(255, 255, 255));
        labelItemsInTheSystem.setText("Items In the System");
        getContentPane().add(labelItemsInTheSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSellerActionPerformed
      // functions: method that open a new window accordin to the desition of the user (What want to do) and 
        //close the actual window

        WindowDesitionOfTheSeller window = new WindowDesitionOfTheSeller();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSellerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowConsultOfTheSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowConsultOfTheSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowConsultOfTheSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowConsultOfTheSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowConsultOfTheSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackWindowConsultOfTheSalesToWindowDesitionOfTheSeller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelIdentification;
    private javax.swing.JLabel labelIdentification1;
    private javax.swing.JLabel labelItemsInTheSystem;
    private javax.swing.JLabel labelItemsSold;
    private javax.swing.JLabel labelItemsUnsold;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName1;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelQuantity1;
    private javax.swing.JList squareListOfProductSold;
    private javax.swing.JList squareListOfProductUnsold;
    // End of variables declaration//GEN-END:variables
}
