/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

import javax.swing.DefaultListModel;

/**
 *
 * @author Juliana
 */
public class WindowAvailableProductInSystem extends javax.swing.JFrame {

    /**
     * Creates
     * .new form WindowAvailableProductInSystem
     */
    
    public void printProductInTheSquare(){
      
                /*inputs: none
        output: add to the DefaultListModel (squareLisOfProductSeeAlltheElement) the name of the product and 
        the quantity
        restrictions: none
        functions: each product in the Global.productList is added to thereby be displayed by the 
        user in the product properties list (name of the product and quantity available)
        */ 
        
        DefaultListModel name = (DefaultListModel) squareLisOfProductSeeAlltheElement.getModel();
        for(Product product : Global.productList){
            name.addElement(product.getName() + "          :          " + product.getQuantityAvailable() + "                 :" + product.getIdProduct());
        }
    }
    
    public WindowAvailableProductInSystem() {
        
                /*inputs: none
        output: Available Product will become visible above the screen
        restrictions: none
        functions: after performing various functions as focusing screen
        writing what was asked ect is sent to the method printProductInTheSquare 
        */ 
        
        initComponents();
        this.setTitle("Available Product");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        printProductInTheSquare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottonBackWindowAvailableProductInSystemToWindowOption = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        squareLisOfProductSeeAlltheElement = new javax.swing.JList();
        buttonSeeDetailOfProduct = new javax.swing.JButton();
        labelListOfProduct = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        labelIdentification = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottonBackWindowAvailableProductInSystemToWindowOption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bottonBackWindowAvailableProductInSystemToWindowOption.setText("Back");
        bottonBackWindowAvailableProductInSystemToWindowOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonBackWindowAvailableProductInSystemToWindowOptionActionPerformed(evt);
            }
        });
        getContentPane().add(bottonBackWindowAvailableProductInSystemToWindowOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        squareLisOfProductSeeAlltheElement.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(squareLisOfProductSeeAlltheElement);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 182));

        buttonSeeDetailOfProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonSeeDetailOfProduct.setText("See Details");
        buttonSeeDetailOfProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeeDetailOfProductActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSeeDetailOfProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        labelListOfProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelListOfProduct.setForeground(new java.awt.Color(255, 255, 255));
        labelListOfProduct.setText("List Of Product In System");
        getContentPane().add(labelListOfProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 19, -1, -1));

        labelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("Name");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        labelAmount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelAmount.setForeground(new java.awt.Color(255, 255, 255));
        labelAmount.setText("Amount");
        getContentPane().add(labelAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        labelIdentification.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelIdentification.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentification.setText("Identification");
        getContentPane().add(labelIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/12055294_1007424805986273_1091806738_o.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonBackWindowAvailableProductInSystemToWindowOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonBackWindowAvailableProductInSystemToWindowOptionActionPerformed
        
                /*
        functions: the current screen is closed after sending the user to the screen WindowOption
        */  
        
        
        WindowOption window = new WindowOption();
        window.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bottonBackWindowAvailableProductInSystemToWindowOptionActionPerformed

    private void buttonSeeDetailOfProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeeDetailOfProductActionPerformed
       
               /*inputs: none
        output: none
        restrictions: none
        functions: You get the selected item by the user and then searches this
        product gets the item selected by the user then the identification of the product which
        is sent to the function identificationOfTheProductToSeeDetails is obtained and then the
        user is sent to the window WindowShowAllTheDetailsOfTheProduct
        */ 
        
        if(squareLisOfProductSeeAlltheElement.getSelectedValue() == null){
              return;
          }  
        
        String elementSelected = squareLisOfProductSeeAlltheElement.getSelectedValue().toString();
        String [] chain = elementSelected.split(":");
        int identificationOfTheProduct=  Integer.parseInt(chain[2]);
        
        System.out.println("ID: " + identificationOfTheProduct);

        Global.identificationOfTheProductToSeeDetails = identificationOfTheProduct;
        
        WindowShowAllTheDetailsOfTheProduct window = new WindowShowAllTheDetailsOfTheProduct();
        window.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_buttonSeeDetailOfProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowAvailableProductInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowAvailableProductInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowAvailableProductInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowAvailableProductInSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowAvailableProductInSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonBackWindowAvailableProductInSystemToWindowOption;
    private javax.swing.JButton buttonSeeDetailOfProduct;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelIdentification;
    private javax.swing.JLabel labelListOfProduct;
    private javax.swing.JLabel labelName;
    private javax.swing.JList squareLisOfProductSeeAlltheElement;
    // End of variables declaration//GEN-END:variables
}
